<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="ova" nsURI="https://uet-dse.org/ocl/validation-algebra/1.0" nsPrefix="ova">

  <eClassifiers xsi:type="ecore:EEnum" name="AlgebraStage">
    <eLiterals name="SEMANTIC" value="0"/>
    <eLiterals name="OPTIMIZED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeKind">
    <eLiterals name="BOOLEAN" value="0"/>
    <eLiterals name="INTEGER" value="1"/>
    <eLiterals name="REAL" value="2"/>
    <eLiterals name="STRING" value="3"/>
    <eLiterals name="OBJECT" value="4"/>
    <eLiterals name="COLLECTION" value="5"/>
    <eLiterals name="CLASS_REFERENCE" value="6"/>
    <eLiterals name="BOTTOM" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionKind">
    <eLiterals name="NONE" value="0"/>
    <eLiterals name="COLLECTION" value="1"/>
    <eLiterals name="SET" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LiteralKind">
    <eLiterals name="NULL" value="0"/>
    <eLiterals name="BOTTOM" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="INTEGER" value="3"/>
    <eLiterals name="REAL" value="4"/>
    <eLiterals name="STRING" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
    <eLiterals name="NOT" value="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
    <eLiterals name="AND" value="0"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="XOR" value="2"/>
    <eLiterals name="IMPLIES" value="3"/>
    <eLiterals name="EQ" value="4"/>
    <eLiterals name="NEQ" value="5"/>
    <eLiterals name="LT" value="6"/>
    <eLiterals name="LE" value="7"/>
    <eLiterals name="GT" value="8"/>
    <eLiterals name="GE" value="9"/>
    <eLiterals name="ADD" value="10"/>
    <eLiterals name="SUBTRACT" value="11"/>
    <eLiterals name="MULTIPLY" value="12"/>
    <eLiterals name="DIVIDE" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CallKind">
    <eLiterals name="METHOD" value="0"/>
    <eLiterals name="COLLECTION_OPERATION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IteratorKind">
    <eLiterals name="EXISTS" value="0"/>
    <eLiterals name="FORALL" value="1"/>
    <eLiterals name="SELECT" value="2"/>
    <eLiterals name="REJECT" value="3"/>
    <eLiterals name="COLLECT" value="4"/>
    <eLiterals name="IS_UNIQUE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NavigationDirection">
    <eLiterals name="OUTGOING" value="0"/>
    <eLiterals name="INCOMING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NavigationPredicateKind">
    <eLiterals name="EXISTS" value="0"/>
    <eLiterals name="NOT_EXISTS" value="1"/>
    <eLiterals name="FORALL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidationModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" lowerBound="1" defaultValueLiteral="ova-certified-v1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="certificationProfile" lowerBound="1" defaultValueLiteral="OCL_VAL_FINITE_SET_V1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariants" upperBound="-1" containment="true" eType="#//Invariant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invariant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invariantId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stage" lowerBound="1" defaultValueLiteral="SEMANTIC" eType="#//AlgebraStage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="producerVersion" lowerBound="1" defaultValueLiteral="semantic-ir-v1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selfVariable" lowerBound="1" containment="true" eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//TypeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionKind" lowerBound="1" defaultValueLiteral="NONE" eType="#//CollectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" containment="true" eType="#//TypeDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredType" lowerBound="1" containment="true" eType="#//TypeDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" lowerBound="1" containment="true" eType="#//TypeDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1" eType="#//VariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//LiteralKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="#//UnaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="#//BinaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBranch" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBranch" lowerBound="1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LetExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1" containment="true" eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredType" lowerBound="1" containment="true" eType="#//TypeDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeAccessExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1" containment="true" eType="#//AttributeReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1" eType="#//NavigationDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualified" defaultValueLiteral="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationAccessExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" lowerBound="1" containment="true" eType="#//NavigationReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiers" upperBound="-1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callKind" lowerBound="1" eType="#//CallKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" containment="true" eType="#//TypeDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IteratorExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//IteratorKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" lowerBound="1" containment="true" eType="#//TypeDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" lowerBound="1" containment="true" eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationPredicateExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//NavigationPredicateKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" lowerBound="1" containment="true" eType="#//NavigationAccessExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" containment="true" eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationCountExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparisonOperator" lowerBound="1" eType="#//BinaryOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" lowerBound="1" containment="true" eType="#//NavigationAccessExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" containment="true" eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" containment="true" eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationUniquenessExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" lowerBound="1" containment="true" eType="#//NavigationAccessExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" lowerBound="1" containment="true" eType="#//VariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" containment="true" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projection" lowerBound="1" containment="true" eType="#//Expression"/>
  </eClassifiers>
</ecore:EPackage>