# Neo4j Sync Settings - UET DSE Plugin
# Created on: 2023-10-27
# Note: true = Immediate/Auto Sync, false = Manual Sync (Default)

# --- Outgoing Sync (USE -> Neo4j) ---
# Tu dong day Model len Neo4j khi n?p file .use
autoPushModelOnImport=false

# Tu dong cap nhat Object khi co thay doi (Add/Edit/Delete) trong USE
autoPushObjectOnChange=false

# --- Incoming Sync (Neo4j -> USE) ---
# Tu dong nhan thay doi Model tu Database ngay lap tuc
autoPullModelOnChange=false

# Tu dong nhan thay doi Object tu Database ngay lap tuc
autoPullObjectOnChange=false