<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="nva" nsURI="https://uet-dse.org/nva/1.0" nsPrefix="nva">

  <eClassifiers xsi:type="ecore:EEnum" name="NvaTypeKind">
    <eLiterals name="BOOLEAN" value="0"/>
    <eLiterals name="INTEGER" value="1"/>
    <eLiterals name="REAL" value="2"/>
    <eLiterals name="STRING" value="3"/>
    <eLiterals name="OBJECT" value="4"/>
    <eLiterals name="SET" value="5"/>
    <eLiterals name="BOTTOM" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NvaLiteralKind">
    <eLiterals name="NULL" value="0"/>
    <eLiterals name="BOTTOM" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="INTEGER" value="3"/>
    <eLiterals name="REAL" value="4"/>
    <eLiterals name="STRING" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NvaCompareOperator">
    <eLiterals name="EQ" value="0"/>
    <eLiterals name="NEQ" value="1"/>
    <eLiterals name="LT" value="2"/>
    <eLiterals name="LE" value="3"/>
    <eLiterals name="GT" value="4"/>
    <eLiterals name="GE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NvaArithmeticOperator">
    <eLiterals name="ADD" value="0"/>
    <eLiterals name="SUBTRACT" value="1"/>
    <eLiterals name="MULTIPLY" value="2"/>
    <eLiterals name="DIVIDE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NvaSetRelationOperator">
    <eLiterals name="INCLUDES_ALL" value="0"/>
    <eLiterals name="EXCLUDES_ALL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NvaSetCombinationOperator">
    <eLiterals name="UNION" value="0"/>
    <eLiterals name="INTERSECTION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NvaNavigationDirection">
    <eLiterals name="OUTGOING" value="0"/>
    <eLiterals name="INCOMING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" lowerBound="1" defaultValueLiteral="nva-certified-v1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="certificationProfile" lowerBound="1" defaultValueLiteral="OCL_VAL_FINITE_SET_V1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariants" upperBound="-1" containment="true" eType="#//NvaInvariant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaInvariant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invariantId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="producerVersion" lowerBound="1" defaultValueLiteral="t-norm-v1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selfVariable" lowerBound="1" containment="true" eType="#//NvaVariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//NvaTypeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaVariableDeclaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredType" lowerBound="1" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaExpression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultType" lowerBound="1" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaVariable" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1" eType="#//NvaVariableDeclaration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaLiteral" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//NvaLiteralKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lexicalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaSetLiteral" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" lowerBound="1" upperBound="-1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaAttribute" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaNavigation" abstract="true" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="associationKey" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" lowerBound="1" eType="#//NvaNavigationDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifiers" upperBound="-1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaNavigationOne" eSuperTypes="#//NvaNavigation">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaNavigationMany" eSuperTypes="#//NvaNavigation">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaViewSet" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" lowerBound="1" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaAllInstances" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classKey" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaNot" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaAnd" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaOr" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaCompare" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="#//NvaCompareOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaArithmetic" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="#//NvaArithmeticOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaCoerce" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" lowerBound="1" containment="true" eType="#//NvaType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetType" lowerBound="1" containment="true" eType="#//NvaType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaIf" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenBranch" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBranch" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaLet" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" lowerBound="1" containment="true" eType="#//NvaVariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaIterator" abstract="true" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" lowerBound="1" containment="true" eType="#//NvaType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" lowerBound="1" containment="true" eType="#//NvaVariableDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaExists" eSuperTypes="#//NvaIterator">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaSelect" eSuperTypes="#//NvaIterator">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaCollect" eSuperTypes="#//NvaIterator">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaIsUnique" eSuperTypes="#//NvaIterator">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaSetRelation" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="#//NvaSetRelationOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" lowerBound="1" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaSetCombination" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1" eType="#//NvaSetCombinationOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" lowerBound="1" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaAsSet" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" lowerBound="1" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaCount" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceCollectionType" lowerBound="1" containment="true" eType="#//NvaType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaTypeKindOf" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassKey" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NvaCast" eSuperTypes="#//NvaExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassName" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetClassKey" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1" containment="true" eType="#//NvaExpression"/>
  </eClassifiers>
</ecore:EPackage>