<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="ocltypes" nsURI="https://uet-dse.org/ocl/type-system/1.0" nsPrefix="ocltypes">

  <eClassifiers xsi:type="ecore:EEnum" name="ScalarTypeKind">
    <eLiterals name="VOID" value="0"/>
    <eLiterals name="OCL_ANY" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="INTEGER" value="3"/>
    <eLiterals name="REAL" value="4"/>
    <eLiterals name="STRING" value="5"/>
    <eLiterals name="UNLIMITED_NATURAL" value="6"/>
    <eLiterals name="ENUM" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionTypeKind">
    <eLiterals name="COLLECTION" value="0"/>
    <eLiterals name="SET" value="1"/>
    <eLiterals name="BAG" value="2"/>
    <eLiterals name="SEQUENCE" value="3"/>
    <eLiterals name="ORDERED_SET" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConformanceRuleKind">
    <eLiterals name="REFLEXIVE" value="0"/>
    <eLiterals name="VOID_BOTTOM" value="1"/>
    <eLiterals name="OCL_ANY_TOP" value="2"/>
    <eLiterals name="INTEGER_TO_REAL" value="3"/>
    <eLiterals name="UNLIMITED_NATURAL_TO_INTEGER" value="4"/>
    <eLiterals name="UML_GENERALIZATION" value="5"/>
    <eLiterals name="COLLECTION_COVARIANCE" value="6"/>
    <eLiterals name="GENERIC_COLLECTION" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclTypeSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profile" lowerBound="1" defaultValueLiteral="OCL_TYPE_CONFORMANCE_V1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifiers" upperBound="-1" containment="true" eType="#//UmlClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalizations" upperBound="-1" containment="true" eType="#//UmlGeneralization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="certifiedJudgements" upperBound="-1" containment="true" eType="#//ConformanceJudgement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmlClassifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UmlGeneralization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" lowerBound="1" eType="#//UmlClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1" eType="#//UmlClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OclType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScalarType" eSuperTypes="#//OclType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//ScalarTypeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassType" eSuperTypes="#//OclType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" lowerBound="1" eType="#//UmlClassifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionType" eSuperTypes="#//OclType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//CollectionTypeKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1" containment="true" eType="#//OclType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConformanceJudgement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="judgementId" lowerBound="1" iD="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actual" lowerBound="1" containment="true" eType="#//OclType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declared" lowerBound="1" containment="true" eType="#//OclType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rule" lowerBound="1" eType="#//ConformanceRuleKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalizationPath" upperBound="-1" eType="#//UmlGeneralization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementWitness" containment="true" eType="#//ConformanceJudgement"/>
  </eClassifiers>
</ecore:EPackage>